Document additions in the 4.2.0 RC
TheSharks/WildBeastDocs pull request #17
Opened 2017-01-26 17:56 UTC by LWTechGaming

Prepare the documentation for the release of version 4.2.0. Quality control requested from the PR developers (SteamingMutt, zaza7, thenightex, Nenkai).

2017-01-26 20:52 UTC, Nenkai reviewed
Seems to cover everything that was pushed into experimental. +1

2017-01-26 20:53 UTC, Nenkai approved these changes

2017-01-27 02:45 UTC, zaza7 requested changes
It appears we're still missing an updated piece of playlist which is "delete/remove all" to well clear the playlist.

I take that back. I don't like the command. I'd rather it be `playlist clear`

2017-01-27 06:15 UTC, zaza7 approved these changes

2017-01-27 08:19 UTC, Dougley requested changes

2017-01-27 08:19 UTC, SteamingMutt commented on docs/install_windows.md
> +**IMPORTANT NOTE:** Unless you use Elastic and Kibana like we do, **don't modify this unless your instance is and want easier log stashing!**
Akward wording

2017-01-27 08:20 UTC, SteamingMutt commented on docs/install_linux.md
> +**IMPORTANT NOTE:** Unless you use Bezerk, the WildBeast WSM, **do not modify anything here as it's for advanced users only!**
Akward wording

2017-01-27 09:33 UTC, LWTechGaming commented on docs/install_windows.md
> +**IMPORTANT NOTE:** Unless you use Elastic and Kibana like we do, **don't modify this unless your instance is and want easier log stashing!**
That's a typo...

2017-01-27 09:39 UTC, LWTechGaming commented
@SteamingMutt The above has been resolved in https://github.com/TheSharks/WildBeastDocs/pull/17/commits/636ee981030a1ef9a45b3c1bf87af296e3b543e5

2017-01-27 10:13 UTC, Dougley approved these changes

2017-01-27 11:24 UTC, thenightex approved these changes
gw

2017-01-27 14:20 UTC, LWTechGaming commented
Seems good. Just gotta fix blocking issue https://github.com/TheSharks/WildBeastDocs/issues/18

2017-01-27 15:00 UTC, LWTechGaming commented
Docs ready for launch. Going to standby mode for the update push.

2017-01-28 15:01 UTC, merged