Miscellaneous Fixes
TheSharks/WildBeastDocs pull request #26
Opened 2017-06-28 20:44 UTC by caf203

2017-06-28 20:59 UTC, Nenkai commented
👌

2017-06-28 22:05 UTC, Dougley requested changes

2017-06-28 22:05 UTC, SteamingMutt commented on docs/install_windows.md
> +Now, you'd want to figure out where you want the bot to be downloaded. Something simple where you can find it is good, AKA not in the system internals (Possibly some other drive, though **NOT A FLASH
`.git` is correct.

2017-06-28 22:09 UTC, caf203 commented
Yes, I changed that because in the Linux Guide, .git isn't used. I'm trying to enforce a bit of uniformity.

2017-06-28 22:11 UTC, SteamingMutt commented
Enforce using `.git` then 😅

2017-06-28 22:37 UTC, Dougley approved these changes

2017-07-02 11:26 UTC, linuswillner approved these changes
Looks all good to me. Always appreciate me some typo fixes 😄

2017-07-02 11:26 UTC, merged